services:
  biobot:
    build: UI2
    image: biobot:latest
    ports:
      - "5000:5000"
    volumes:
      - ./UI2/docs:/app/docs
      - ./UI2/handlers.json:/app/handlers.json
      - ./UI2:/app:rw
    env_file :
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
    restart : always
    depends_on:
      - postgres
    networks:
      - db
      - biobot


  postgres:
    image: postgres:16
    env_file :
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db

volumes:
  db_data:

networks:
  db:
  biobot:
    name: biobot 